# Generated by Django 4.1.7 on 2023-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_company_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
