# Generated by Django 4.1.7 on 2023-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='versions/', verbose_name='Archivo'),
        ),
    ]
