# Generated by Django 4.1.7 on 2023-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_version_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio anual'),
        ),
        migrations.AddField(
            model_name='program',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='program',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mensual'),
        ),
        migrations.AddField(
            model_name='program',
            name='permanent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio permanente'),
        ),
        migrations.AddField(
            model_name='program',
            name='trial_days',
            field=models.IntegerField(default=0, verbose_name='Días de prueba'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de la suscripción'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('permanent', 'Permanente'), ('trial', 'Prueba')], default='monthly', max_length=20, verbose_name='Tipo de suscripción'),
        ),
    ]
