# Generated by Django 4.1.7 on 2023-03-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_program_annual_price_program_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='trial_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Días de prueba'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
